export {default as Homescreen} from './Homscreen'
export {default as Authentication} from './Authentication'
export {default as PersonalForm } from './Resume-Form/PersonalForm'
export {default as ProfessionalDetails } from './Resume-Form/ProfessionalDetails'
export {default as Skills } from './Resume-Form/Skills'
export {default as WorkExperience } from './Resume-Form/WorkExperience'
export {default as Education } from './Resume-Form/Education'
export {default as Projects } from './Resume-Form/Additional-Information/Projects'
export {default as Awards } from './Resume-Form/Additional-Information/Awards'
export {default as  Publications} from './Resume-Form/Additional-Information/Publications'
export {default as References } from './Resume-Form/Additional-Information/References'
export {default as Additional } from './Resume-Form/Additional-Information/AdditionDetail'
